# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
	# Web Server
	config.vm.define "web" do |web|
		web.vm.hostname = "web"
		web.vm.box = "apache"
		web.vm.network "forwarded_port", guest: 80, host: 8080
  		web.vm.network "private_network", type: "dhcp"
		web.vm.provision "chef_solo" do |chef|
        	chef.add_recipe "vagrant_la"
	end
end


  #MySQL Server
  config.vm.define "db" do |db|
		db.vm.hostname = "db"
		db.vm.box = "mysql"
		db.vm.network "private_network", type: "dhcp"
	end
end


