# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
  # you will need to install plugin vagrant-omnibus on your machine https://github.com/chef/vagrant-omnibus
  # reach-chef uses an older chef
  config.omnibus.chef_version = "11.6.0"
  
  # make sure these ports are free on your system if you get network connection errors
  config.vm.network "forwarded_port", guest: 80, host: 9090
  
  # creates a private network so you can ping it like any other server
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provision "chef_solo" do |chef|
    chef.roles_path = "your path to /reach-chef/roles"
    chef.cookbooks_path = ["your path to /reach-chef/cookbooks", "your path to /reach-chef/site-cookbooks"]
    chef.data_bags_path = "your path to /reach-chef/data_bags"
    # any role you want to test add it here
    # chef.add_role "your role goes here"
    # any recipe you want to test add it here
    # chef.add_recipe "your recipe goes here"
  end
end
